### ISSUE TITLE
想请教一个问题：可否用于比对

### ISSUE THREAD

**Issue by SpecterHi** [AlfnXd/video_clipper#1]
如果我们提供的人脸照片不是从原视频中得到的，可以通过这个项目来检测出此人出现的时间段吗？
谢谢！

**Comment by corberan** [comment]
可以啊，选尽量和视频里的面孔接近的近期照片就行

**Comment by SpecterHi** [comment]
您好，请问具体是在哪一步将这些照片加入呢？
按照您的教程，在运行聚类和手动标识之后，感觉最后的video_clipping.py速度飞快，我还以为是直接根据自动截图的文件名来判断在原始视频中出现的时间段的，其实并非如此吗？

**Comment by corberan** [comment]
聚类和标记完成之后，哪个面孔出现在哪些帧这件事已经确定了，时间段自然也就确定了。video_clipping 按给定的间隔将帧数（存在截图的文件名里）集合转化为具体的时段，只是一个简单的计算，所以飞快，就是你想的那样。真正繁重的计算工作在聚类那一步已经完成了。

将一段视频中所有的面孔提取出来进行聚类分离，得到某个人出现的时间段，结果会相对准确一些。我一开始也是想用一个已知数据去和出现的各个面孔做比对，用分数阈值来区分，但是效果是很糟糕的，阈值也不好定。而且很显然，一个已知的数据和视频里的这个人总会因为年代、妆容等等因素有或多或少的差别，并不能一劳永逸；直接分析单个视频，只要视频时间跨度不是很大，那这个人在各个时段出现的脸总是相似的，聚类总能有很好的结果，用来解决【视频中人脸出现时段】这一单一业务是比较合适的。

如果只是想知道怎么对比照片，那简单了解一下 dlib 库即可。[https://github.com/ageitgey/face_recognition](https://github.com/ageitgey/face_recognition) 就是对 dlib 库的一个封装，有助于加强了解。

**Comment by corberan** [comment]
@SpecterHi

**Comment by SpecterHi** [comment]
非常感谢您的工作和认真的解说，谢谢！
您提到的这个项目我也尝试过啦。
那我自己去做一些工程层面的工作看看怎么整合。
再次感谢！
